-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 13:47:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `PaymentMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentMethod` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PaymentMethod` (
  `idPaymentMethod` INT NOT NULL AUTO_INCREMENT,
  `PaymentMethodLabel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaymentMethod`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPaymentMethod_UNIQUE` ON `PaymentMethod` (`idPaymentMethod` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PaymentMethodcol_UNIQUE` ON `PaymentMethod` (`PaymentMethodLabel` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PaymentMethodEnterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentMethodEnterprise` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PaymentMethodEnterprise` (
  `PaymentMethod_idPaymentMethod` INT NOT NULL,
  `Enterprise_idEnterprise` INT NOT NULL,
  PRIMARY KEY (`PaymentMethod_idPaymentMethod`, `Enterprise_idEnterprise`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quote` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Quote` (
  `idQuote` INT NOT NULL AUTO_INCREMENT,
  `quoteLabel` VARCHAR(45) NOT NULL,
  `quoteSubject` VARCHAR(45) NOT NULL,
  `Enterprise_idEnterprise` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`Enterprise_idEnterprise`, `Product_idProduct`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idQuote_UNIQUE` ON `Quote` (`idQuote` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `address` (
  `idAddress` INT(11) NOT NULL,
  `homeNumber` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Commune_idCommune` INT(11) NOT NULL,
  `codeZip` VARCHAR(45) NOT NULL,
  PRIMARY KEY USING BTREE (`homeNumber`, `floor`, `street`, `city`, `Commune_idCommune`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idAddress_UNIQUE` ON `address` (`idAddress` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `buyer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buyer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `buyer` (
  `idBuyer` INT(11) NOT NULL,
  `firstNameB` VARCHAR(45) NOT NULL,
  `lastNameB` VARCHAR(45) NOT NULL,
  `birthDayB` DATE NOT NULL,
  `Address_idAddress` INT(11) NULL DEFAULT NULL,
  `emailBuyer` VARCHAR(45) NOT NULL,
  `phoneBuyer` VARCHAR(45) NOT NULL,
  `buyerStatus` ENUM('person', 'enterprise') NOT NULL,
  `registerCommercialNumberB` VARCHAR(45) NULL DEFAULT NULL,
  `taxIdentificationNumberB` VARCHAR(45) NULL DEFAULT NULL,
  `webSiteB` VARCHAR(45) NULL DEFAULT NULL,
  `articleBuyer` VARCHAR(45) NULL DEFAULT NULL,
  `enterpriseNameBuyer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`firstNameB`, `lastNameB`, `birthDayB`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idBuyer_UNIQUE` ON `buyer` (`idBuyer` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `commune`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commune` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `commune` (
  `idCommune` INT(11) NOT NULL,
  `communeName` VARCHAR(45) NOT NULL,
  `Wilaya_idWilaya` INT(11) NOT NULL,
  PRIMARY KEY USING BTREE (`communeName`, `Wilaya_idWilaya`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCommune_UNIQUE` USING BTREE ON `commune` (`idCommune`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contact` (
  `idContact` INT(11) NOT NULL,
  `firstNameS` VARCHAR(45) NOT NULL,
  `lastNameS` VARCHAR(45) NOT NULL,
  `birthDayS` DATE NOT NULL,
  `Address_idAddress` INT(11) NOT NULL,
  `emailSeller` VARCHAR(45) NOT NULL,
  `phoneSeller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`firstNameS`, `lastNameS`, `birthDayS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idContact_UNIQUE` USING BTREE ON `contact` (`idContact`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `delivery` (
  `idDelivery` INT(11) NOT NULL,
  `deliveryNumber` VARCHAR(45) NOT NULL,
  `Buyer_idBuyer` INT(11) NOT NULL,
  `startDateDelivery` DATE NOT NULL,
  `Enterprise_idEnterprise` INT(11) NOT NULL,
  `Order_idOrder` INT(11) NOT NULL,
  `Address_idAddress` INT(11) NOT NULL,
  `endDateDelivery` DATE NOT NULL,
  `deliveryEmail` VARCHAR(45) NOT NULL,
  `deliveryPhone` VARCHAR(45) NOT NULL,
  `deliveryStatus` ENUM('inProgress', 'waiting', 'delivered') NOT NULL,
  `deliveryType` ENUM('home', 'adaptedPoint', 'pointSeller') NOT NULL,
  `deliveryDuration` INT(11) NOT NULL,
  `linkGPS` VARCHAR(45) NOT NULL,
  `deliveryPoint` VARCHAR(45) NOT NULL,
  PRIMARY KEY USING BTREE (`deliveryNumber`, `startDateDelivery`, `Enterprise_idEnterprise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDelivery_UNIQUE` ON `delivery` (`idDelivery` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Delivery_Order_idx` ON `delivery` (`Order_idOrder` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `deliverypoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliverypoint` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `deliverypoint` (
  `Address_idAddress` INT(11) NOT NULL,
  `Enterprise_idEnterprise` INT(11) NOT NULL,
  `deliveryPointName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Enterprise_idEnterprise`, `Address_idAddress`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `fk_DeliveryPoint_Enterprise_idx` ON `deliverypoint` (`Enterprise_idEnterprise` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enterprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enterprise` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enterprise` (
  `idEnterprise` INT(11) NOT NULL,
  `enterpriseName` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `Contact_idContact` INT(11) NOT NULL,
  `Address_idAddress` INT(11) NOT NULL,
  `webSite` VARCHAR(45) NOT NULL,
  `taxIdentificationNumberS` VARCHAR(45) NOT NULL,
  `registerCommercialNumberS` VARCHAR(45) NOT NULL,
  `accountNumber` VARCHAR(45) NOT NULL,
  `accountType` VARCHAR(45) NOT NULL,
  `publicPrivate` ENUM('Public', 'Private') NOT NULL,
  `logoImage` VARCHAR(45) NOT NULL,
  `transportCosts` FLOAT NOT NULL,
  `deliveryTime` INT(11) NOT NULL,
  `reservationTime` INT(11) NOT NULL,
  `acceptationTime` INT(11) NOT NULL DEFAULT 24,
  `validationTime` INT(11) NOT NULL DEFAULT 20,
  `orderRecoveryTime` INT(11) NOT NULL DEFAULT 3,
  `articleSeller` VARCHAR(45) NOT NULL,
  `enterpriseStatus` ENUM('active', 'noActive') NOT NULL DEFAULT 'active',
  `activationPeriod` INT NOT NULL,
  `activationDate` DATE NOT NULL,
  `acceptationAfterSendDocuments` INT NULL,
  `advancementAmount` DOUBLE NULL,
  PRIMARY KEY (`enterpriseName`, `town`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idEnterprise_UNIQUE` ON `enterprise` (`idEnterprise` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `enterpriseName_UNIQUE` USING BTREE ON `enterprise` (`enterpriseName`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orderline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderline` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orderline` (
  `idOrderLine` INT(11) NOT NULL,
  `Order_idOrder` INT(11) NOT NULL,
  `Product_idProduct` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `total` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Order_idOrder`, `Product_idProduct`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idOrderLine_UNIQUE` ON `orderline` (`idOrderLine` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_OrderLine_Order_idx` ON `orderline` (`Order_idOrder` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orderpay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderpay` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orderpay` (
  `idOrder` INT(11) NOT NULL,
  `Enterprise_idEnterprise` INT(11) NOT NULL,
  `Buyer_idBuyer` INT(11) NOT NULL,
  `orderNumber` VARCHAR(45) NOT NULL,
  `dateOrder` DATETIME NOT NULL,
  `totalOutsideTax` FLOAT NOT NULL,
  `orderTotal` FLOAT NOT NULL,
  `orderStatus` ENUM('initial', 'notConfirm', 'reservationRequest', 'reserved', 'cancel', 'paid') NOT NULL,
  `tva` FLOAT NULL DEFAULT NULL,
  `cancellationReason` VARCHAR(255) NULL DEFAULT NULL,
  `acceptationDate` TIMESTAMP NULL DEFAULT NULL,
  `reservationDate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`idOrder`, `Enterprise_idEnterprise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idOrder_UNIQUE` ON `orderpay` (`idOrder` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Order_Enterprise_idx` ON `orderpay` (`Enterprise_idEnterprise` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product` (
  `idProduct` INT(11) NOT NULL,
  `productRef` VARCHAR(45) NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `Enterprise_idEnterprise` INT(11) NOT NULL,
  `price` FLOAT NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `productImage` VARCHAR(255) NOT NULL,
  `quantityStock` INT(11) NOT NULL,
  `productDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY USING BTREE (`productRef`, `productName`, `Enterprise_idEnterprise`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idProduct_UNIQUE` ON `product` (`idProduct` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `transaction` (
  `idTransaction` INT(11) NOT NULL,
  `transactionNumber` VARCHAR(45) NOT NULL,
  `transactionDate` DATETIME NOT NULL,
  `Order_idOrder` INT(11) NOT NULL,
  `Buyer_idBuyer` INT(11) NOT NULL,
  `Enterprise_idEnterprise` INT(11) NOT NULL,
  `transactionStatus` ENUM('success', 'failed', 'cancel', 'waiting') NOT NULL,
  `paymentMethod` ENUM('dahabia', 'bank card', 'bank transfer', 'cash payment', 'payment installment') NOT NULL,
  `failureDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`transactionNumber`, `transactionDate`, `Order_idOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idTransaction_UNIQUE` ON `transaction` (`idTransaction` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Transaction_Order_idx` ON `transaction` (`Order_idOrder` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wilaya`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wilaya` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wilaya` (
  `idWilaya` INT(11) NOT NULL,
  `wilayaName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`wilayaName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idWilaya_UNIQUE` ON `wilaya` (`idWilaya` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `wilayaName_UNIQUE` USING BTREE ON `wilaya` (`wilayaName`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `PaymentMethod`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `PaymentMethod` (`idPaymentMethod`, `PaymentMethodLabel`) VALUES (1, 'DAHABIA');
INSERT INTO `PaymentMethod` (`idPaymentMethod`, `PaymentMethodLabel`) VALUES (2, 'BANK CARD');
INSERT INTO `PaymentMethod` (`idPaymentMethod`, `PaymentMethodLabel`) VALUES (3, 'PAYMENT INSTALLMENT');
INSERT INTO `PaymentMethod` (`idPaymentMethod`, `PaymentMethodLabel`) VALUES (4, 'BANK TRANSFER');
INSERT INTO `PaymentMethod` (`idPaymentMethod`, `PaymentMethodLabel`) VALUES (5, 'CASH PAYMENT');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
